name: Checkout
description: Checkout repository for pull requests and branches
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 0
        fetch-tags: true
