name: 'Shared Checkout'
description: 'Checkout repository with common configuration'

inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 0
        fetch-tags: true
        token: ${{ inputs.token }} 