- name: Add apt repository for Saltstack (arm)
  block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Salt Project public key
      ansible.builtin.get_url:
        url: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
        dest: /etc/apt/keyrings/salt-archive-keyring.pgp
        mode: '0644'

    - name: Add Salt repository sources
      ansible.builtin.get_url:
        url: https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources
        dest: /etc/apt/sources.list.d/salt.sources
        mode: '0644'
  when: platform == "arm64"

- name: Add apt repository for Saltstack (amd)
  block:
    - name: salt gpg key
      ansible.builtin.apt_key:
        url: https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
        keyring: /etc/apt/trusted.gpg.d/salt-archive-keyring-2023-amd.gpg

    - name: salt apt repo
      ansible.builtin.apt_repository:
         repo: deb [signed-by=/etc/apt/trusted.gpg.d/salt-archive-keyring-2023-amd.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/{{ salt_minon_version }} focal main
         state: present
  when: platform == "amd64"

- name: Salt minion install
  apt:
    name: salt-minion
