- name: ensure services are stopped
  community.general.snap:
    name: amazon-ssm-agent
    state: absent
  when: debpkg_mode or stage2_nix

- name: ensure services are stopped and disabled for first boot
  systemd:
    enabled: no
    name: '{{ item }}'
    state: stopped
  with_items:
    - snapd
    - postgresql
    - pgbouncer
    - fail2ban
    - motd-news
    - vector
  when: debpkg_mode or stage2_nix

- name: Remove snapd
  apt:
    state: absent
    pkg:
      - snapd
  when: debpkg_mode or stage2_nix

- name: ensure services are stopped and disabled for first boot
  systemd:
    enabled: no
    name: '{{ item }}'
    state: stopped
    masked: yes
  with_items:
    - lvm2-monitor
  when: debpkg_mode or stage2_nix

- name: disable man-db
  become: yes
  file:
    state: absent
    path: "/etc/cron.daily/{{ item }}"
  with_items:
    - man-db
    - popularity-contest
    - ubuntu-advantage-tools
  when: debpkg_mode or stage2_nix
