- hosts: localhost
  become: yes

  vars:
    sql_files:
      - "/tmp/ansible-playbook/files/pgbouncer_config/pgbouncer_auth_schema.sql"
      - "/tmp/ansible-playbook/files/stat_extension.sql"


  tasks:
    - set_fact:
        supabase_internal: true
      tags:
        - install-supabase-internal

    - set_fact:
        parallel_jobs: 16

    - name: stat unit test file copy
      copy:
        src: /tmp/unit-tests/unit-test-01.sql
        dest: /home/postgres/unit-test-01.sql
        # state: present
        owner: postgres
        group: postgres
        mode: '0644'

    - name: locale-gen
      command: sudo locale-gen en_US.UTF-8

    # - name: Ensure en_US.UTF-8 locale is enabled
    #   shell: |
    #     echo "LC_ALL=en_US.UTF-8" >> /etc/environment
    #     echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    #     echo "LANG=en_US.UTF-8" > /etc/locale.conf
    #     locale-gen en_US.UTF-8      
    #   become: yes

    - name: check locales
      command: locale -a
      register: locales 

    - name: Install Postgres from nix binary cache
      import_tasks: stage2-setup-postgres.yml

    - name: First boot optimizations
      import_tasks: optimizations.yml

    - name: Run unit tests
      import_tasks: test-image.yml
      tags:
        - unit-tests
        
    - name: Check if postgres user is part of users group
      shell: "id -nG postgres | grep -qw users"
      register: check_user_group
      ignore_errors: yes
      become: yes
      args:
        executable: /bin/bash

    - name: Print result to Ansible log output
      debug:
        msg: "The postgres user is {{ 'not ' if check_user_group.rc != 0 else '' }}part of the users group"

    - name: Install osquery from nixpkgs binary cache
      become: yes
      shell: |
        sudo -u ubuntu bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install nixpkgs#osquery"

    - name: Run osquery permission checks
      become: yes
      shell: |
        sudo -u ubuntu bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && /usr/bin/python3 /tmp/ansible-playbook/files/permission_check.py"

    - name: Remove osquery    
      become: yes
      shell: |
        sudo -u ubuntu bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile remove osquery"
