- name: Create pgbouncer user
  user:
    name: pgbouncer
    shell: /bin/false
    comment: PgBouncer user
    groups: postgres,ssl-cert
  when: nixpkg_mode

- name: PgBouncer - create a directory if it does not exist
  file:
    path: /etc/pgbouncer
    state: directory
    owner: pgbouncer
    group: pgbouncer
    mode: '0700'
  when: nixpkg_mode

- name: PgBouncer - create a directory if it does not exist
  file:
    state: directory
    owner: pgbouncer
    group: pgbouncer
    path: '{{ item }}'
    mode: '0775'
  with_items:
    - '/etc/pgbouncer-custom'
  when: nixpkg_mode

- name: create placeholder config files
  file:
    path: '/etc/pgbouncer-custom/{{ item }}'
    state: touch
    owner: pgbouncer
    group: pgbouncer
    mode: 0664
  with_items:
    - 'generated-optimizations.ini'
    - 'custom-overrides.ini'
    - 'ssl-config.ini'
  when: nixpkg_mode

- name: PgBouncer - adjust pgbouncer.ini
  copy:
    src: files/pgbouncer_config/pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: pgbouncer
    mode: '0700'
  when: nixpkg_mode

- name: PgBouncer - create a directory if it does not exist
  file:
    path: /etc/pgbouncer/userlist.txt
    state: touch
    owner: pgbouncer
    mode: '0700'
  when: nixpkg_mode

- name: import /etc/tmpfiles.d/pgbouncer.conf
  template:
    src: files/pgbouncer_config/tmpfiles.d-pgbouncer.conf.j2
    dest: /etc/tmpfiles.d/pgbouncer.conf
  become: yes
  when: nixpkg_mode

- name: PgBouncer - By default allow ssl connections.
  become: yes
  copy:
    dest: /etc/pgbouncer-custom/ssl-config.ini
    content: |
      client_tls_sslmode = allow
  when: nixpkg_mode

- name: Grant pg_hba and pgbouncer grp perm for adminapi updates
  shell: |
     chmod g+w /etc/postgresql/pg_hba.conf
     chmod g+w /etc/pgbouncer-custom/ssl-config.ini
  when: nixpkg_mode

# Add fail2ban filter
- name: import jail.d/pgbouncer.conf
  template:
    src: files/fail2ban_config/jail-pgbouncer.conf.j2
    dest: /etc/fail2ban/jail.d/pgbouncer.conf
  become: yes
  when: nixpkg_mode

- name: import filter.d/pgbouncer.conf
  template:
    src: files/fail2ban_config/filter-pgbouncer.conf.j2
    dest: /etc/fail2ban/filter.d/pgbouncer.conf
  become: yes
  when: nixpkg_mode

# Add systemd file for PgBouncer
- name: PgBouncer - import postgresql.service
  template:
    src: files/pgbouncer_config/pgbouncer.service.j2
    dest: /etc/systemd/system/pgbouncer.service
  become: yes
  when: nixpkg_mode

- name: install pgbouncer from supabase nix binary cache
  become: yes
  shell: |
    sudo -u pgbouncer bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install github:supabase/postgres/{{ git_commit_sha }}#pgbouncer"
  when: stage2_nix

- name: PgBouncer - reload systemd
  systemd:
    daemon_reload: yes
  when: stage2_nix
