- name: PostgREST - system user
  user: name=postgrest

- name: PostgREST - install from nix postgrest flakes
  become: yes
  shell: |
    sudo -u postgrest bash -c ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install --accept-flake-config github:postgrest/postgrest/v{{ postgrest_release }}"
  when: stage2_nix

- name: Create symlink for PostgREST from Nix profile to /opt
  ansible.builtin.file:
    src: /home/postgrest/.nix-profile/bin/postgrest
    dest: /opt/postgrest
    state: link
    force: yes  # This will replace existing file/symlink if it exists

- name: create directories
  file:
    state: directory
    owner: postgrest
    group: postgrest
    mode: '0775'
    path: /etc/postgrest

- name: empty files
  file:
    state: touch
    owner: postgrest
    group: postgrest
    path: /etc/postgrest/{{ item }}
  with_items:
    - base.conf
    - generated.conf

- name: create conf merging script
  copy:
    content: |
      #! /usr/bin/env bash
      set -euo pipefail
      set -x

      cd "$(dirname "$0")"
      cat $@ > merged.conf
    dest: /etc/postgrest/merge.sh
    mode: 0750
    owner: postgrest
    group: postgrest

- name: PostgREST - create service files
  template:
    src: files/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - postgrest.service
    - postgrest-optimizations.service

- name: PostgREST - reload systemd
  systemd:
    daemon_reload: yes
