name: Check shell scripts

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkout:
    uses: ./.github/workflows/shared-checkout.yml

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v4
        with:
          name: repository
          path: .

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2001 -e SC2002 -e SC2143
        with:
          scandir: './ansible/files/admin_api_scripts'

      - name: Run ShellCheck on pg_upgrade scripts
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2001 -e SC2002 -e SC2143
        with:
          scandir: './ansible/files/admin_api_scripts/pg_upgrade_scripts'
