name: Release 15.6 on Dockerhub

on:
  push:
    branches:
      - develop
      - sam/docker-int-test
    paths:
      - ".github/workflows/dockerhub-release-15-6.yml"
      - "common-nix.vars*"
jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      docker_version: ${{ steps.settings.outputs.postgres-version }}
      image_tag: supabase/postgres:${{ steps.settings.outputs.postgres-version }}
      build_args: ${{ steps.args.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - id: settings
        # Remove spaces and quotes to get the raw version string
        run: sed -r 's/(\s|\")+//g' common-nix.vars.pkr.hcl >> $GITHUB_OUTPUT
      - id: args
        uses: mikefarah/yq@master
        with:
          cmd: yq 'to_entries | map(select(.value|type == "!!str")) |  map(.key + "=" + .value) | join("\n")' 'ansible/vars.yml'

  build_release_image:
    needs: [settings]
    strategy:
      matrix:
        include:
          - runner: [self-hosted, X64]
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 180
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: build
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: |
            ${{ needs.settings.outputs.build_args }}
          target: production
          tags: ${{ needs.settings.outputs.image_tag }}_${{ matrix.arch }}-dev
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=${{ github.ref_name }}-latest-${{ matrix.arch }}-dev
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-latest-${{ matrix.arch }}-dev
          file: "Dockerfile-156"
          outputs: type=docker,dest=/tmp/image.tar
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK }}
          SLACK_USERNAME: "gha-failures-notifier"
          SLACK_COLOR: "danger"
          SLACK_MESSAGE: "Building Postgres ${{ matrix.arch }} image failed"
          SLACK_FOOTER: ""
  supabase_test:
    needs: [settings, build_release_image]
    strategy:
      matrix:
        include:
          - runner: [self-hosted, X64]
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - run: docker load < /tmp/image.tar
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: |
          supabase init
          mkdir -p supabase/.temp
          echo "${{ needs.settings.outputs.docker_version }}" > supabase/.temp/postgres-version
      - run: supabase start
        env:
          SUPABASE_INTERNAL_IMAGE_REGISTRY: docker.io
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK }}
          SLACK_USERNAME: "gha-failures-notifier"
          SLACK_COLOR: "danger"
          SLACK_MESSAGE: "Supabase test failed on ${{ matrix.arch }}"
          SLACK_FOOTER: ""
  push_image:
    needs: [settings, build_release_image, supabase_test]
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docker-image-${{ matrix.arch }}
          path: /tmp
      - run: docker load < /tmp/image.tar
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        run: docker push ${{ needs.settings.outputs.image_tag }}-dev

  # merge_manifest:
  #   needs: [settings, build_release_image]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Merge multi-arch manifests
  #       run: |
  #         docker buildx imagetools create -t ${{ needs.settings.outputs.image_tag }} \
  #         ${{ needs.settings.outputs.image_tag }}_amd64 \
  #         ${{ needs.settings.outputs.image_tag }}_arm64
  #     - name: Slack Notification
  #       if: ${{ failure() }}
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK }}
  #         SLACK_USERNAME: "gha-failures-notifier"
  #         SLACK_COLOR: "danger"
  #         SLACK_MESSAGE: "Building Postgres image failed"
  #         SLACK_FOOTER: ""

  # publish:
  #   needs: [settings, merge_manifest]
  #   # Call workflow explicitly because events from actions cannot trigger more actions
  #   uses: ./.github/workflows/mirror.yml
  #   with:
  #     version: ${{ needs.settings.outputs.docker_version }}
  #   secrets: inherit
