name: Publish Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-17
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
