name: Shared Checkout

on:
  workflow_call:
    # No inputs needed as we're using the default GitHub context

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
      repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: .
          retention-days: 1 